services:
#    pro_address_app.example:
#        class: ProAddress\AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    pa.stat:
        class: ProAddress\AppBundle\Stat\Stat
        arguments: ["@doctrine.orm.entity_manager"]
