<?php

namespace ProAddress\AnnonceBundle\Repository;

/**
 * ACategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ACategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
