<?php

namespace ProAddress\UserBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class ProAddressUserBundle extends Bundle
{
    public function getParent()
    {
        return 'FOSUserBundle'; // TODO: Change the autogenerated stub
    }
}
