pro_address_service_s_categorie:
    resource: "@ProAddressServiceBundle/Controller/SCategorieController.php"
    type:     annotation

pro_address_app_categorie:
    resource: "@ProAddressAppBundle/Controller/CategorieController.php"
    type:     annotation

pro_address_app:
    resource: "@ProAddressAppBundle/Resources/config/routing.yml"
    prefix:   /

pro_address_recrutement_recrutement:
    resource: "@ProAddressRecrutementBundle/Controller/RecrutementController.php"
    type:     annotation

pro_address_recrutement:
    resource: "@ProAddressRecrutementBundle/Resources/config/routing.yml"
    prefix:   /recrutements

pro_address_service:
    resource: "@ProAddressServiceBundle/Resources/config/routing.yml"
    prefix:   /services

pro_address_user_utilisateur:
    resource: "@ProAddressUserBundle/Controller/UtilisateurController.php"
    type:     annotation

pro_address_app_structure:
    resource: "@ProAddressAppBundle/Controller/StructureController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
