<?php

namespace ProAddress\ServiceBundle\Repository;

/**
 * SCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
