pa_service:
    path:     /{cat}/{cp}/{page}
    defaults: { _controller: ProAddressServiceBundle:Index:content, cat: all, cp: oo, page: 1 }
    requirements:
        cat:  ^[a-z-]{2,50}
        cp: \w{2}
        page: \d{1,3}
