pa_service:
    path:     /{cat}/{cp}/{page}/{id}
    defaults: { _controller: ProAddressServiceBundle:Index:content, cat: all, cp: oo, page: 1, id: 0 }
    requirements:
        cat:  ^[a-z|-]{2,50}
        cp: \w{2}
        page: \d{1,3}
        id: \d{1,15}